### ISSUE TITLE
Only getting one entry into the database???

### ISSUE THREAD

**Issue by J4YpL4Y** [siegmund0/Dayz-Leaderboard-Web-Developer#1]
Hi  siegmund0 

Can you help me with this issue.  I have most of this working however i can only get one entry into the database.  This entry gets updated every 60sec.  The details change player name ect......

![Capture](https://user-images.githubusercontent.com/71966676/95376797-8b203000-08d9-11eb-8a1e-d3e417cfe9e4.JPG)

**Comment by J4YpL4Y** [comment]
My PK was an INT changed it to VARCHAR and its sorted

**Comment by rjclarkewp007** [comment]
Hey i cannot get this working..

what should the columns be set to?

![image](https://user-images.githubusercontent.com/13123792/108484244-4ef7d580-72a4-11eb-967d-2beeb095decc.png)

**Comment by Erreur32** [comment]
![image](https://user-images.githubusercontent.com/2248137/162386961-4992902c-6e92-4a0c-9036-083119ab0a46.png)

I have this on mine , it's working well ;)

_oups maybe to late for the reply ^^_
